### ISSUE TITLE
Provide additional OS information

### ISSUE THREAD

**Issue by marko-asplund** [trustin/os-maven-plugin#15]
It would be very beneficial to provide the following additional OS info:
- major version of the detected OS release (e.g. `os.detected.release.version.major`)
- glibc version (esp. major), for Linux based systems
- OS kernel version (esp. major)

**Comment by trustin** [comment]
Partially fixed by #16 (OS version)

@marko-asplund Are you interested in sending the PRs for the others?

**Comment by lukejackson** [comment]
Any chance the OS version change can be released to Maven Central first? This is already a very useful addition which I'm looking forward to using.

**Comment by trustin** [comment]
@lukejackson Will release now. Sorry for getting late.

**Comment by trustin** [comment]
Released. Should be in the central repo now.

**Comment by lukejackson** [comment]
Thanks Trustin

On 23 Mar 2016, at 20:52, Trustin Lee <notifications@github.com> wrote:

Released. Should be in the central repo now.
