### ISSUE TITLE
os-maven-plugin doesn't support IBM's Power8 little endian system

### ISSUE THREAD

**Issue by jackyh** [trustin/os-maven-plugin#3]
Hi, Trustin,

I'm from IBM Power8 ecosystem team. Since your plugin is used widely in many maven controlled projects, I am trying to port it to Power8 little endian machine. It's os.arch value is ppc64le, so what's your suggestion on how to modify this code piece in the src of this plugin:
in file: main/java/kr/motd/maven/os/Detector.java:

I modified like this:

      if (value.equals("ppc64le")) {
            return "ppc_64_le";
        }

**Comment by trustin** [comment]
Solved by @r4f4's patch - dc58a0973fda90f448d073093bf08440a39ab4ca
