### ISSUE TITLE
Could be nice to have a os.detected.arch.bitness variable

### ISSUE THREAD

**Issue by jflecomte** [trustin/os-maven-plugin#36]
I had a case where I needed to know the "bitness" of the OS (32 or 64 bits). I used ${os.detected.arch}, but I was not interested in the architecture part (x86, itanium, etc.), I only needed the bitness part. So it would be nice to have a ${os.detected.arch.bitness} variable containing only the bitness part of ${os.detected.arch}.

**Comment by trustin** [comment]
Sounds like a good idea. Let me try to find some spare time.

**Comment by bmhm** [comment]
This would be a great feature. Is this still being worked on?

**Comment by trustin** [comment]
Couldn't find spare time for this. Pull request appreciated.

**Comment by bmhm** [comment]
@trustin please review PR https://github.com/trustin/os-maven-plugin/pull/41

**Comment by bmhm** [comment]
@trustin Please kindly see my pull request. :-)

**Comment by bmhm** [comment]
@trustin 
I think I might write my own native lib loader. :-(

**Comment by trustin** [comment]
I'm really sorry I forgot about your pull request. Let me take a look this week. Is it still valid?

**Comment by bmhm** [comment]
Yes, it is. But: I created a different type of build right now, so I might not actually use it.
