### ISSUE TITLE
Version 1.6.0 has stopped working...??

### ISSUE THREAD

**Issue by harleydaves** [trustin/os-maven-plugin#38]
Today (1/11/19) os-maven-plugin v:1.6.0 is suddenly not providing: ${os.detected.classifier}.

**Comment by trustin** [comment]
I don't see any noticeable degradation. Is this still an issue?

**Comment by juebanlin** [comment]
ctrl+s保存后触发的编译不能获得${os.detected.classifier}变量值

**Comment by trustin** [comment]
Let me close this issue since I didn't hear anything since the initial report and it seems to work OK for me.
