### ISSUE TITLE
Detected os.name when running on Apple Silicon M1

### ISSUE THREAD

**Issue by aalmiray** [trustin/os-maven-plugin#58]
Apparently Zulu reports the value of "os.name" to be "Mac".
The code currently looks for "macosx" or "osx".

**Comment by tresf** [comment]
Hmm... Homebrew's OpenJDK 16.0.1, `os.name` returns `Mac OS X`, but `${os.detected.name}` still comes back as `osx`.  Any idea why it doesn't behave the same?

```bash
$(brew --prefix openjdk)/bin/java -XshowSettings:properties -version 2>&1 |grep os.name
#    os.name = Mac OS X
```
