### ISSUE TITLE
Get this on Maven central?

### ISSUE THREAD

**Issue by timboudreau** [trustin/os-maven-plugin#7]
I notice [NetBeans](http://netbeans.org) marks all Netty projects as "unloadable" (you can build, but it can't figure out the classpath, etc.) unless I've built the right tag of this project locally.  Would be nice if tools could download it.

**Comment by trustin** [comment]
I'm not sure, but it's already on the central: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22os-maven-plugin%22

Please let me know if I got your problem wrong.

**Comment by nmittler** [comment]
Pretty sure we can close this.  @trustin?

**Comment by trustin** [comment]
Oh yeah. :-)
